### ISSUE TITLE
Ethereum Cat Herders Meeting #128

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/PM#398]
## Date and Time

26 March 2024 at **14:00 UTC** [Please note the change of meeting time]

## Location 

Join Zoom Meeting
https://us02web.zoom.us/j/84834303064?pwd=YTVDNUxvSjEzL1VTOXNoNmI1a2RlZz09

## Agenda

New users on ECH Discord and/or contributor's introduction

### 1. ECH updates 

- [ECH: Reviewing Q1, Roadmap Q2–2024 and beyond!](https://medium.com/p/f776878a1a9c/edit)
#### ECH Operations 
  - [Meet The Herders](https://www.youtube.com/playlist?list=PL4cwHXAawZxqFcgyfjAcUAeoanC2RgUbF) 
    - [x] Medium blogpost (mirror.xyz ?)
    - [x] Video
    - [ ] Podcast
  - ECH Engineering
     -  New website domain - https://EthCatHerders.com
     - [ECH Website](https://www.ethcatherders.com/) 
       - [x] New Home page
     - [Existing ECH website](https://www.ethereumcatherders.com/) 
       - [x] [Ethereum Testnets](https://www.ethereumcatherders.com/testnets/)
       - [x] Meet The Herders [proposed design](https://www.figma.com/file/uXsNK9RsQs9xtT71LKsGL0/Ethereum-Cat-Herders?type=design&node-id=531-2&mode=design)
       - [x] Ecosystem Project Demo [Proposed design] - TBA
      - Meetings, Podcast, EPD, Twitter spaces
        - [x] All Wallet Dev
        - [ ] [Ecosystem Project Demo](https://www.youtube.com/playlist?list=PL4cwHXAawZxrhbMXuCqMsCiwx1lwu_cNs)
        - [x] [ECH Podcast](https://open.spotify.com/show/7dgxKMkSyy3HWtQW7OfqXA)
        - [x] Twitter spaces - thoughts/ideas/volunteers
      - EIPsInsight, PEEPanEIP, YT Shorts, WiEP, Meetings, misc support
        - [x] [EIPsInsight website](https://eipsinsight.com/insight/2024/3) 
        - [PEEPanEIP](https://www.youtube.com/playlist?list=PL4cwHXAawZxqu0PKKyMzG_3BJV_xZTi1F)  
          - [EIP-7002: Execution Layer Triggerable exits with Danny Ryan](https://github.com/ethcatherders/PM/projects/2#card-91637103) on March 28 at 18:30 UTC
          - [EIP-7547: Inclusion List with Mike Neuder, Terence and Fransesco](https://github.com/ethcatherders/PM/projects/2#card-91336613) on April 03 at 18:30 UTC
          - [RIP-7212: Precompile for secp256r1 Curve Support with Ulaş Erdoğan](https://github.com/ethcatherders/PM/projects/2#card-90571888) on Apr 09, 2024 at 18:30 UTC
          - Upcoming meetings can be found on [PEEPanEIP schedule](https://github.com/ethereum-cat-herders/PM/projects/2)
       - [YouTube Shorts](https://studio.youtube.com/playlist/PL4cwHXAawZxr020waJCI0dZAfPAW2naK1/videos)- Goal share one shorts per week
         - [Community Playlist](https://www.youtube.com/playlist?list=PL4cwHXAawZxr020waJCI0dZAfPAW2naK1)
        - [PEEPanEIP is an incredible Ethereum resource - Danny Ryan](https://www.youtube.com/shorts/QDwVL0_s4cs)
         - [Ethereum specs and research are open and accessible to the community - DappLion ](https://www.youtube.com/shorts/GxX-dI13adQ)
         - [EthResearch is a great place to start with Ethereum](https://www.youtube.com/shorts/RuBuSUtgDu0)
       - WiEP next meeting is April 5th at 14:00 UTC 
       - Other Meetings
         - [ ] All ERC Dev
         - [x] eth_multicall Playlist
         - [x] EOF Implementers Meeting Playlist
         - [x] MaxEB [Breakout Room 3](https://github.com/ethereum/pm/issues/993) Calendar update
         - [x] EIPIP Meeting Playlist, next meeting [Agenda](https://github.com/ethcatherders/EIPIP/issues/326)
         - [x] ECH Meeting Playlist
      - ECH Funding
        - [ ] Octant - [Epoch 3](https://discuss.octant.app/t/ethereum-cat-herders/91/3)
        - [ ] Any other grant suggestions?
        - A bunch of retroactive requests
     - [Meeting notes](https://docs.google.com/spreadsheets/d/1axM1KaKc-GCcoPbAnYTOhgLnxXsBVoO5XRjTN3CLnck/edit#gid=0) and action items for ECH 
       - [ ] All Core Dev Execution [184]
       - [ ] All Core Dev Consensus [129]
       - [ ] EIPIP meeting [101]
       - [ ] EIP Editing Office Hour Meeting [Agenda 35](https://github.com/ethcatherders/EIPIP/issues/328), Recording [34]()

 
### 2. Other Protocol & Application Development
- [MEV Community Call 8](https://t.co/9vI1hLEziG) and [notes](https://twitter.com/terencechain/status/1760344174598266904)
- [Ethereum Sequencing and Preconfirmations Call #4](https://youtu.be/IsYISmTmPmQ)
- EOF Implementers Call [38](https://youtu.be/bjcTxsTWd4w)
- [eth_multicall Meeting [March 25, 2024]](https://youtu.be/8uXmfXv4jvs)
- Verkle Implementers [Call #14](https://youtu.be/0Zd4zK2Zupg)
- [Inclusion List Breakout Room #2 [2024-03-18]](https://youtube.com/live/GVdkDXZTtnw)

### 3. Events, Fellowship, Hackathon
- [Academic Grant by EF](https://esp.ethereum.foundation/academic-grants)
- [Eth Berlin](https://ethberlin.org/) - May 24-26, 2024

#### Dencun
  - [Dencun: Deneb-Cancun Upgrade
Fun fact, mainnet live stream details, POAP, NFT & what’s next?](https://medium.com/ethereum-cat-herders/dencun-deneb-cancun-upgrade-e84e2055768c)
  - [Learn2Earn - Dencun NFT](https://medium.com/ethereum-cat-herders/learn2earn-is-back-with-dencun-nft-3712d2b086fd). Try [app](https://l2e.ethereumcatherders.com/) today!
#### Next Upgrade
- [Prague/Electra Network Upgrade Meta Thread](https://ethereum-magicians.org/t/prague-electra-network-upgrade-meta-thread/16809)
- [EIP-7600: Hardfork Meta - Prague/Electra](https://github.com/ethereum/EIPs/pull/8121)

####  Useful resources
- Prague/Electra [Playlist](https://www.youtube.com/playlist?list=PL4cwHXAawZxqOHV_F40AJbzcl8b6tG8xw)
- Light client [roadmap for Electra](https://hackmd.io/@etan-status/electra-lc) by Etan Kissling
  - [EVM Object Format (EOF) with Danno Ferrin](https://youtu.be/rlZwPuF149U)
  - [EVM Object Format (EIP-3540 & EIP-3670) with Andrei Maiboroda](https://youtu.be/GMeRA-xPp-E)
  - [EIP-6110: Supply validator deposits on chain](https://youtu.be/tRTBgCN9VgY)
  - [EIP-2537 in five slides](https://youtu.be/al4YpfDVmS4)

### 5. New initiative/association/team discussion
- Staking related content
- Potential new ideas for community engagement

### 6. General updates/discussion
- ECH Stats.
    - [Twitter](https://twitter.com/EthCatHerders) - 6770 Followers
    - [Discord](https://discord.io/EthCatHerders) - 2255 users
    - [YouTube](https://studio.youtube.com/channel/UCD9iiIwTRtLDYcEWONs2Q3A) - 3246 subscribers
    - [LinkedIn](https://www.linkedin.com/company/ethereum-cat-herders/) - 300 Followers

### 7. Review of outstanding action items from previous ECH meetings
- Meeting [127]

## The date for the next meeting is April 09, 2023 at 14:00 UTC

 (If anything else, leave a comment.)
