### ISSUE TITLE
Ethereum Cat Herders Meeting #129

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/PM#399]
## Date and Time

 ~~April 9,~~ April 23, 2024 at **14:00 UTC** [Please note the change of meeting time]

## Location 

Join Zoom Meeting
https://us02web.zoom.us/j/84834303064?pwd=YTVDNUxvSjEzL1VTOXNoNmI1a2RlZz09

## Agenda

New users on ECH Discord and/or contributor's introduction

#### ECH Operations 
 - [Meet The Herders](https://www.youtube.com/playlist?list=PL4cwHXAawZxqFcgyfjAcUAeoanC2RgUbF) -  [George](https://youtu.be/lnlGqdf4ukY)
    - [x] Medium blogpost (mirror.xyz ?)
    - [x] Video
    - [x] Podcast
  - ECH Engineering
     -  New website domain - https://EthCatHerders.com
     - [ECH Website](https://www.ethcatherders.com/) 
       - [x] New Home page
       - [x] Adding Discourse
     - [Existing ECH website](https://www.ethereumcatherders.com/) 
       - [x] Meet The Herders [proposed design](https://www.figma.com/file/uXsNK9RsQs9xtT71LKsGL0/Ethereum-Cat-Herders?type=design&node-id=531-2&mode=design)
       - [x] Ecosystem Project Demo [Proposed design] - TBA
      - Meetings, Podcast, EPD, Twitter spaces
        - [x] All Wallet Dev
        - [x] [Ecosystem Project Demo](https://www.youtube.com/playlist?list=PL4cwHXAawZxrhbMXuCqMsCiwx1lwu_cNs)
        - [x] [ECH Podcast](https://open.spotify.com/show/7dgxKMkSyy3HWtQW7OfqXA)
        - [x] Twitter spaces - thoughts/ideas/volunteers
      - EIPsInsight, PEEPanEIP, YT Shorts, WiEP, Meetings, misc support
        - [x] [EIPsInsight website](https://eipsinsight.com/insight/2024/3) 
        - [PEEPanEIP](https://www.youtube.com/playlist?list=PL4cwHXAawZxqu0PKKyMzG_3BJV_xZTi1F)  
          - [EIP-7002: Execution Layer Triggerable exits with Danny Ryan](https://github.com/ethcatherders/PM/projects/2#card-91637103) 
          - [EIP-7547: Inclusion List with Mike Neuder, Terence and Fransesco](https://github.com/ethcatherders/PM/projects/2#card-91336613) on April 16 at 18:30 UTC
          - [RIP-7212: Precompile for secp256r1 Curve Support with Ulaş Erdoğan](https://github.com/ethcatherders/PM/projects/2#card-90571888) on Apr 09, 2024 at 18:30 UTC
          - Upcoming meetings can be found on [PEEPanEIP schedule](https://github.com/ethereum-cat-herders/PM/projects/2)
       - [YouTube Shorts](https://studio.youtube.com/playlist/PL4cwHXAawZxr020waJCI0dZAfPAW2naK1/videos)- Goal share one shorts per week
         - [Community Playlist](https://www.youtube.com/playlist?list=PL4cwHXAawZxr020waJCI0dZAfPAW2naK1)
        - [PEEPanEIP is an incredible Ethereum resource - Danny Ryan](https://www.youtube.com/shorts/QDwVL0_s4cs)
         - [Ethereum specs and research are open and accessible to the community - DappLion ](https://www.youtube.com/shorts/GxX-dI13adQ)
         - [EthResearch is a great place to start with Ethereum](https://www.youtube.com/shorts/RuBuSUtgDu0)
       - WiEP next meeting is ~~April 12th at 14:00 UTC~~ TBA 
       - Other Meetings
         - [x] [All ERC Dev](https://www.youtube.com/playlist?list=PL4cwHXAawZxqF_gL0CXz9RgjEbSXQhX70)
         - [x] eth_multicall Playlist
         - [x] EOF Implementers Meeting Playlist
         - [x] MaxEB [Breakout Room 3](https://github.com/ethereum/pm/issues/993) Calendar update
         - [x] EIPIP Meeting Playlist, next meeting [Agenda](https://github.com/ethcatherders/EIPIP/issues/326)
         - [x] [ECH Meeting Playlist](https://www.youtube.com/playlist?list=PL4cwHXAawZxogBKmFamsYqUch8xEu55y2)
      - ECH Funding
        - [x] Octant - [Epoch 3](https://discuss.octant.app/t/ethereum-cat-herders/91/3)
        - [x] Any other grant suggestions?
        - A bunch of retroactive requests
     - [Meeting notes](https://docs.google.com/spreadsheets/d/1axM1KaKc-GCcoPbAnYTOhgLnxXsBVoO5XRjTN3CLnck/edit#gid=0) and action items for ECH 
       - [ ] All Core Dev Execution [184](https://github.com/ethereum/pm/pull/1004)
       - [ ] All Core Dev Consensus [131]
       - [ ] EIPIP meeting [101](https://github.com/ethcatherders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20101.md)
       - [ ] EIP Editing Office Hour Meeting [Agenda 36](https://github.com/ethcatherders/EIPIP/issues/330), Recording [35](https://youtu.be/IW44XMTqTS0)
- [ECH: Reviewing Q1, Roadmap Q2–2024 and beyond!](https://medium.com/p/f776878a1a9c/edit)

New Task: https://github.com/ethereum/pm/blob/master/Archive/Dencun/dencun-pm.md#devnets
 
### 2. Other Protocol & Application Development
- Ethereum Sequencing and Preconfirmations [Call #5](https://youtu.be/8HFVnb69zUI)
- eth_multicall Meeting [April 08, 2024](https://youtu.be/2E10m2zpojM)
- Verkle Implementers [Call 16](https://youtu.be/R-Jo2Lci0zc)
- EOF Implementers Meeting 40  [April 03, 2024](https://youtu.be/HZ457PnRDqI)

### 3. Events, Fellowship, Hackathon
- [Eth Berlin](https://ethberlin.org/) - May 24-26, 2024
- [Eth CC, Paris](https://ethcc.io/) JULY 8-11, 2024

### 4. Ethereum network upgrades
- [Prague/Electra Network Upgrade Meta Thread](https://ethereum-magicians.org/t/prague-electra-network-upgrade-meta-thread/16809)
- [EIP-7600: Hardfork Meta - Prague/Electra](https://github.com/ethereum/EIPs/pull/8121)

####  Useful resources
- Prague/Electra [Playlist](https://www.youtube.com/playlist?list=PL4cwHXAawZxqOHV_F40AJbzcl8b6tG8xw)
- Light client [roadmap for Electra](https://hackmd.io/@etan-status/electra-lc) by Etan Kissling
  - [EVM Object Format (EOF) with Danno Ferrin](https://youtu.be/rlZwPuF149U)
  - [EVM Object Format (EIP-3540 & EIP-3670) with Andrei Maiboroda](https://youtu.be/GMeRA-xPp-E)
  - [EIP-6110: Supply validator deposits on chain](https://youtu.be/tRTBgCN9VgY)
  - [EIP-2537 in five slides](https://youtu.be/al4YpfDVmS4)

### 5. New initiative/association/team discussion
- Staking related content
- Potential new ideas for community engagement

### 6. General updates/discussion
- ECH Stats.
    - [Twitter](https://twitter.com/EthCatHerders) - 6889 Followers
    - [Discord](https://discord.io/EthCatHerders) - 2389 users
    - [YouTube](https://studio.youtube.com/channel/UCD9iiIwTRtLDYcEWONs2Q3A) - 3390 subscribers
    - [LinkedIn](https://www.linkedin.com/company/ethereum-cat-herders/) - 300 Followers

### 7. Review of outstanding action items from previous ECH meetings
- Meeting [128](https://github.com/ethcatherders/PM/blob/2cc7f9ea6a3812bd17620355897fa2f45d90192e/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%20128.md)

## The date for the next meeting is May 07, 2023 at 14:00 UTC

 (If anything else, leave a comment.)

**Comment by poojaranjan** [comment]
Closing in favor of #401
